### ISSUE TITLE
Noisy output generated follow the Inference section

### ISSUE THREAD

**Issue by abc2cba** [CVMI-Lab/TEXGen#4]
After setting up the conda env and download ckpts,  only noisy textures are generated.
![c59a495347994fc08d9eacaff902d100](https://github.com/user-attachments/assets/3108e029-fccb-4178-924a-353fe9c35f17)
![3441609f539b46b38e7ab1213660cf3e](https://github.com/user-attachments/assets/9765348c-b2c2-402b-8aaa-88c401e9e4c5)
id c59a495347994fc08d9eacaff902d100, 3441609f539b46b38e7ab1213660cf3e

**Comment by XinYu-Andy** [comment]
Did you correctly load the checkpoint?

**Comment by abc2cba** [comment]
Yes, the checkpoint is downloaded from [huggingface](https://huggingface.co/Andyx/TEXGen/blob/main/texgen_v1.ckpt)，and  place to assets/checkpoints/

**Comment by XinYu-Andy** [comment]
Can you try the docker image to check if this issue still exists?

**Comment by abc2cba** [comment]
> Can you try the docker image to check if this issue still exists?

https://hub.docker.com/r/anonymous076/texgen_release, Is this image the latest one? This docker image got stuck after executing the command "docker run -it anonymous076/texgen_release bash"

**Comment by XinYu-Andy** [comment]
> > Can you try the docker image to check if this issue still exists?
> 
> https://hub.docker.com/r/anonymous076/texgen_release, Is this image the latest one? This docker image got stuck after executing the command "docker run -it anonymous076/texgen_release bash"

Please check the updated readme, we update the docker image address.

**Comment by abc2cba** [comment]
Rerun the inference code and the generated texture is as expected now.
